# coding: utf-8

# flake8: noqa
"""
    CrudSQL API

    A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models CrudSQL provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger documentation - Multiple database support (SQL & NoSQL)

    The version of the OpenAPI document: 1.0.0
    Contact: taqi@mobix.biz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.api_error_response import ApiErrorResponse
from openapi_client.models.api_field_schema import ApiFieldSchema
from openapi_client.models.api_model_schema import ApiModelSchema
from openapi_client.models.api_relationship_schema import ApiRelationshipSchema
from openapi_client.models.query_entity_with_relations import QueryEntityWithRelations
from openapi_client.models.query_filter_response import QueryFilterResponse
from openapi_client.models.query_query_filter import QueryQueryFilter
